name: Merge from Master to Beta

on:
  push:
    branches:
      - master

jobs:
  mergeMasterBeta:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git identity
      run: |
        git config --global user.email "actions@rizzle.com"
        git config --global user.name "actions"

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch entire git history
        token: ${{ secrets.MY_CUSTOM_TOKEN }}

    - name: Merge development -> staging
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: master
        target_branch: beta
        github_token: ${{ secrets.MY_CUSTOM_TOKEN }}
    # - name: Merge master into beta
    #   run: |
    #     git checkout master
    #     git fetch origin
    #     git checkout beta
    #     git pull
    #     git merge --no-commit master || (echo "CONFLICT: Merge conflict detected" && git merge --abort && exit 1)
    #     git push -u origin beta
    - name: Send Slack
      if: ${{ failure() }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        text: Merge conflicts occurred when merging master into beta. Please resolve <!subteam^U02U7L6G5P>.