name: Update Value for !latest code

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            script: |
              whoami
              cd /Users/vivek/Documents/ae-automation-renderer
              chmod +x updatehash.sh
              ./updatehash.sh ${{ github.sha }}
